verify

diff --git a/.github/workflows/django-cd.yml b/.github/workflows/django-cd.yml
--- a/.github/workflows/django-cd.yml
+++ b/.github/workflows/django-cd.yml
@@ -13,13 +13,12 @@ jobs:
           fetch-depth: 0
 
       - name: Verify settings_prod.py exists
-        working-directory: ./LIFTEH_project
         run: |
-          ls -la LIFTEH_project/settings_prod.py
-          if [ ! -f "LIFTEH_project/settings_prod.py" ]; then
-            echo "::error::settings_prod.py not found!"
-            exit 1
-          fi
+            ls -la LIFTEH_project/LIFTEH_project/settings_prod.py
+            if [ ! -f "LIFTEH_project/LIFTEH_project/settings_prod.py" ]; then
+              echo "::error::settings_prod.py not found!"
+              exit 1
+            fi
 
       - name: Set up Python 3.8
         uses: actions/setup-python@v5
